# Generated by Django 5.2.3 on 2025-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_base_url',
            field=models.URLField(blank=True, default='', help_text='Base URL for QR code (e.g. https://yourdomain.com)'),
        ),
    ]
