# Generated by Django 5.1.6 on 2025-10-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_ordering', '0003_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='payment_details',
            field=models.TextField(blank=True, default='Refund will be processed to your original payment method'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer')], default='bank_transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_reason',
            field=models.TextField(blank=True, default='Item not available'),
        ),
    ]
