# Generated by Django 5.1.6 on 2025-10-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_ordering', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or location of the table'),
        ),
        migrations.AddField(
            model_name='table',
            name='seats',
            field=models.PositiveIntegerField(default=4, help_text='Number of seats at this table'),
        ),
    ]
