# Generated by Django 5.1.6 on 2025-11-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_ordering', '0007_table_description_table_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Ice Cream Shop', max_length=200)),
                ('shop_description', models.TextField(blank=True, default='Premium ice cream shop serving delicious flavors')),
                ('phone', models.CharField(blank=True, default='+1 (555) 123-4567', max_length=20)),
                ('email', models.EmailField(blank=True, default='info@icecreamshop.com', max_length=254)),
                ('address', models.TextField(blank=True, default='123 Sweet Street, Ice Cream City')),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('INR', 'INR (₹)')], default='INR', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('order_prefix', models.CharField(default='ICE', max_length=10)),
                ('upi_enabled', models.BooleanField(default=True)),
                ('upi_id', models.CharField(blank=True, default='7383712117@yespop', max_length=100)),
                ('upi_merchant_name', models.CharField(blank=True, default='Ice Cream Shop', max_length=100)),
                ('razorpay_enabled', models.BooleanField(default=False)),
                ('razorpay_key_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('smtp_port', models.IntegerField(default=587)),
                ('from_email', models.EmailField(default='vikasmca96@gmail.com', max_length=254)),
                ('from_name', models.CharField(default='Ice Cream Shop', max_length=100)),
                ('email_password', models.CharField(blank=True, max_length=200)),
                ('email_verification_required', models.BooleanField(default=True)),
                ('notify_new_orders', models.BooleanField(default=True)),
                ('notify_payments', models.BooleanField(default=True)),
                ('notify_refunds', models.BooleanField(default=True)),
                ('admin_notification_email', models.EmailField(blank=True, default='admin@icecreamshop.com', max_length=254)),
                ('daily_report_enabled', models.BooleanField(default=False)),
                ('daily_report_time', models.TimeField(blank=True, null=True)),
                ('auto_backup_enabled', models.BooleanField(default=False)),
                ('backup_time', models.TimeField(blank=True, null=True)),
                ('auto_refresh_dashboard', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Shop Settings',
                'verbose_name_plural': 'Shop Settings',
            },
        ),
    ]
